### ISSUE TITLE
Made an Electron version!

### ISSUE THREAD

**Issue by Alex313031** [stignarnia/UniversalPaperclipsButSaves#1] opened 2023-07-08 05:41 UTC
@stignarnia 
"If someone wants to do a proper Electron app or, even better, a GitHub Pages mirror / browser extension that just adds a button to get your save as a file and load it, please do. It's most likely it already exists and I just failed to find it though."

There was not one that I could find.

However, your wish is my command.

Initial repo, I want to add auto saving. > https://github.com/Alex313031/univeral-paperclips-electron

**Comment by stignarnia** [comment] 2023-07-08 06:05
Oh wow, thanks! I'll try it later today, if it works should we merge somehow?

**Comment by Alex313031** [comment] 2023-07-11 13:44
@stignarnia It works fine, you just have to remember to press save or load when opening/closing the app. i would like it to auto save/auto load like the mobile app.
And yeah, we could merge in the future after more work on both our ends.

Do you think you could make it auto-save and auto-load?

Also, in any case, we should modify the CSS of the save/load/reset buttons to match the rest of the buttons used in universal paperclips.

Lastly, I would eventually like to be able to export a save slot to a JSON file, and be able to import it.

This can be done with a chrome extension like

```
chrome.storage.local.get(null, function(items) { // null implies all items
    // Convert object to a string.
    var result = JSON.stringify(items);

    // Save as file
    var url = 'data:application/json;base64,' + btoa(result);
    chrome.downloads.download({
        url: url,
        filename: 'filename_of_exported_file.json'
    });
});
```

But IDK how one would do it natively, because all we have in electron is the native chromium APIs

**Comment by stignarnia** [comment] 2023-07-18 14:55
I fixed the css and did the json thing. I don't understand what you mean by auto save. The problem is that this code is a real mess, not our part but the original, so idk maybe we should fix that before anything else. Anyway, I opened a PR on your repo.

**Comment by Alex313031** [comment] 2023-07-19 02:48
@stignarnia OK nice. Can you change your PR though. Can you restore the .bat and .ps1

**Comment by stignarnia** [comment] 2023-07-19 09:12
Why tough? And by the way you also have editing power on that

**Comment by Alex313031** [comment] 2023-07-19 09:55
@stignarnia OK. And cuz I like to keep stuff around in case I wanna use them lol.

**Comment by stignarnia** [comment] 2023-07-22 13:20
Closing because I'll archive this repo since we have json exports now. Will open a discussion on your repo where we can proceed if you like

**Closed as completed by stignarnia** 2023-07-22 13:20 UTC
